# Travis-CI.org build script

# "trusty" is Ubuntu 14.04.5 LTS
# gcc 4.8.4

dist: trusty

# use containerized infrastructure (for faster startup; no sudo)
sudo: false

language: cpp

compiler:
  - gcc
  - clang

before_script:
    - cat /proc/cpuinfo

    - pip install --user cpp-coveralls
    - BUILD_DIR=$(pwd)
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:~/chime/lib

    - cd
    - wget https://github.com/msgpack/msgpack-c/releases/download/cpp-2.1.0/msgpack-2.1.0.tar.gz
    - tar xzf msgpack-2.1.0.tar.gz
    - export MSGPACK_INC_DIR=$(pwd)/msgpack-2.1.0/include

    - cd
    - ls
    #- git clone https://github.com/zeromq/libzmq.git
    #- git checkout v4.2.1
    #- ./autogen.sh
    - if [ -d "libzmq" ]; then (cd libzmq && git describe) || rm -R libzmq; fi
    - if [ ! -d "libzmq" ]; then (git clone https://github.com/zeromq/libzmq.git && cd libzmq && git checkout v4.2.1 && ./autogen.sh); fi
    - cd libzmq
    #- git pull
    # - wget https://github.com/zeromq/libzmq/releases/download/v4.2.0/zeromq-4.2.0.tar.gz
    # - tar xzf zeromq-4.2.0.tar.gz
    # - cd zeromq-4.2.0
    - ./configure --prefix=${HOME}/zmq --disable-perf --disable-curve -disable-curve-keygen --without-docs
    - make
    - make install
    - export ZMQ_INC_DIR=~/zmq/include
    - export ZMQ_LIB_DIR=~/zmq/lib
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ZMQ_LIB_DIR}
    - export PKG_CONFIG_DIR=${PKG_CONFIG_DIR}:${ZMQ_LIB_DIR}/pkgconfig

    - pip install --user pyzmq
    - pip install --user msgpack-python

    - cd
    - wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp
    - cp zmq.hpp $ZMQ_INC_DIR

    - cd
    - wget https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18.tar.gz
    - tar xzf hdf5-1.8.18.tar.gz
    - cd hdf5-1.8.18
    - ./configure --prefix=$HOME/chime --enable-cxx
    - make all install > log

    - cd
    - git clone https://github.com/CHIMEFRB/ch_frb_io.git
    - cd ch_frb_io
    ### TEMP
    - git checkout webapp
    - ln -s site/Makefile.local.travis Makefile.local
    - pwd
    - make
    - make install

    - cd
    - git clone https://github.com/kmsmith137/simd_helpers.git
    - cd simd_helpers
    ## Goes with bonsai v10
    - git checkout v4_devel
    - ln -s site/Makefile.local.norootprivs Makefile.local
    - make install
    - cd
    - mv include/* chime/include/

    - python -c "import distutils.sysconfig; print(distutils.sysconfig.get_python_inc())"
    #- dpkg -L python-numpy
    - python -c "import sys; print('\n'.join(sys.path))"
    - export PYTHONPATH=${PYTHONPATH}:/usr/lib/python2.7/dist-packages
    - python -c "import numpy; print(numpy.get_include())"
    - pip install --user Cython
    - cython --version

    - cd
    #- git clone https://github.com/kmsmith137/simpulse.git
    - git clone https://github.com/dstndstn/simpulse.git
    - cd simpulse
    ### TEMP
    - git checkout travis
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install

    - cd
    ###- git clone https://github.com/kmsmith137/rf_pipelines.git
    - git clone https://github.com/dstndstn/rf_pipelines.git
    - cd rf_pipelines
    ### TEMP
    - git checkout hdf5conv-2
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install

    - cd
    - git clone https://github.com/kmsmith137/sp_hdf5.git
    - cd sp_hdf5
    - ln -s site/Makefile.local.linux Makefile.local
    - make install
    - cd
    - mv include/* chime/include/

    - cd
    ###- git clone https://github.com/CHIMEFRB/bonsai.git
    ###- git clone https://github.com/dstndstn/bonsai.git
    ###- cd bonsai
    ### TEMP
    ###- git checkout travis
    - mkdir bonsai
    ###- wget http://broiler.astrometry.net/~dstn/temp/bonsai.tar.gz
    - wget http://broiler.astrometry.net/~dstn/temp/bonsai-v10.tar.gz
    - tar xzf bonsai.tar.gz
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install

script:
    - pwd
    - cd $BUILD_DIR
    - pwd
    - ln -s site/Makefile.local.travis Makefile.local
    - make COVERAGE=yes OPTIMIZE=no
    # run some, ahem, unit tests...
    - ./test-l1-rpc &
    - sleep 3
    - python rpc_client.py --shutdown 5555
    - wait
    
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

addons:
  apt:
    packages:
#      - libhdf5-serial-dev
      - liblz4-dev
      - libyaml-cpp-dev
      - libboost-dev
      - libjsoncpp-dev  # for rf_pipelines
      - python-numpy    # for rpc_client.py and simpulse
      - libfftw3-dev    # for simpulse
#      - cython          # for simpulse  -- need a version newer than 0.20.1 ?


# Version in trusty is too old (2.1 vs current = 4.2.0)
#      - libzmq-dev

# see ch_frb_io re: libmsgpack-dev

cache:
  directories:
  - $HOME/libzmq
