# Travis-CI.org build script

# "trusty" is Ubuntu 14.04.5 LTS
# gcc 4.8.4

dist: trusty

# use containerized infrastructure (for faster startup; no sudo)
sudo: false

language: cpp

compiler:
  - gcc
  - clang

before_script:
    - BUILD_DIR=$(pwd)
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:~/chime/lib
    - cd
    - wget https://github.com/msgpack/msgpack-c/releases/download/cpp-2.1.0/msgpack-2.1.0.tar.gz
    - tar xzf msgpack-2.1.0.tar.gz
    - export MSGPACK_INC_DIR=$(pwd)/msgpack-2.1.0/include
    - wget https://github.com/zeromq/libzmq/releases/download/v4.2.0/zeromq-4.2.0.tar.gz
    - tar xzf zeromq-4.2.0.tar.gz
    - cd zeromq-4.2.0
    - ./configure --prefix=${HOME}/zmq --disable-perf --disable-curve -disable-curve-keygen --without-docs
    - make
    - make install
    - export ZMQ_INC_DIR=~/zmq/include
    - export ZMQ_LIB_DIR=~/zmq/lib
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ZMQ_LIB_DIR}
    - cd
    - wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp
    - cp zmq.hpp $ZMQ_INC_DIR
    - git clone https://github.com/CHIMEFRB/ch_frb_io.git
    - cd ch_frb_io
    - ln -s site/Makefile.local.travis Makefile.local
    - pwd
    - make
    - make install

script:
    - pwd
    - cd $BUILD_DIR
    - pwd
    - ln -s site/Makefile.local.travis Makefile.local
    - make

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - liblz4-dev

# Version in trusty is too old (2.1 vs current = 4.2.0)
#      - libzmq-dev

# see ch_frb_io re: libmsgpack-dev

# cache:
#   directories:
#   - $HOME/zeromq-4.2.0
