# Travis-CI.org build script


# To merge:
#   https://github.com/kmsmith137/simpulse/pull/2
#   https://github.com/kmsmith137/simd_helpers/pull/1
#   https://github.com/CHIMEFRB/bonsai/pull/2
#   https://github.com/kmsmith137/rf_pipelines/pull/16


# "trusty" is Ubuntu 14.04.5 LTS
# gcc 4.8.4

dist: trusty

# use containerized infrastructure (for faster startup; no sudo)
sudo: false

language: cpp

compiler:
  - gcc
  - clang

before_script:
    - cat /proc/cpuinfo

    - pip install --user cpp-coveralls
    - pip install --user Cython

    - BUILD_DIR=$(pwd)
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:~/chime/lib

    # Environment variables respected by (some) Makefile.local files
    - export LIBDIR=~/chime/lib
    - export INCDIR=~/chime/include
    - export BINDIR=~/chime/bin
    - export HAVE_PSRFITS=n
    - export HAVE_CH_FRB_IO=y
    - export HAVE_BONSAI=y
    - export PYDIR=~/chime/lib/python2.7/site-packages
    - export PYTHON_INCDIR=/usr/include/python2.7
    - export NUMPY_INCDIR=/usr/lib/python2.7/dist-packages/numpy/core/include
    - export JSONCPP_INC_DIR=/usr/include/jsoncpp

    - export PYTHONPATH=${PYTHONPATH}:/usr/lib/python2.7/dist-packages

    - cd
    - wget https://github.com/msgpack/msgpack-c/releases/download/cpp-2.1.0/msgpack-2.1.0.tar.gz
    - tar xzf msgpack-2.1.0.tar.gz
    - export MSGPACK_INC_DIR=$(pwd)/msgpack-2.1.0/include

    - cd
    - ls
    #- git clone https://github.com/zeromq/libzmq.git
    #- git checkout v4.2.1
    #- ./autogen.sh
    - if [ -d "libzmq" ]; then (cd libzmq && git describe) || rm -R libzmq; fi
    - if [ ! -d "libzmq" ]; then (git clone https://github.com/zeromq/libzmq.git && cd libzmq && git checkout v4.2.1 && ./autogen.sh); fi
    - cd libzmq
    #- git pull
    # - wget https://github.com/zeromq/libzmq/releases/download/v4.2.0/zeromq-4.2.0.tar.gz
    # - tar xzf zeromq-4.2.0.tar.gz
    # - cd zeromq-4.2.0
    - ./configure --prefix=${HOME}/zmq --disable-perf --disable-curve -disable-curve-keygen --without-docs
    - make
    - make install
    - export ZMQ_INC_DIR=~/zmq/include
    - export ZMQ_LIB_DIR=~/zmq/lib
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ZMQ_LIB_DIR}
    - export PKG_CONFIG_DIR=${PKG_CONFIG_DIR}:${ZMQ_LIB_DIR}/pkgconfig

    - pip install --user pyzmq
    - pip install --user msgpack-python

    - cd
    - wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp
    - cp zmq.hpp $ZMQ_INC_DIR

    # Cached hdf5 source code install
    - cd
    - if [ -d "hdf5" ]; then (cd hdf5 && make all install) || rm -R hdf5; fi
    - if [ ! -d "hdf5" ]; then (wget https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18.tar.gz && tar xzf hdf5-1.8.18.tar.gz && mv hdf5-1.8.18 hdf5 && cd hdf5 && ./configure --prefix=$HOME/chime --enable-cxx && make all install); fi
    #- tar xzf hdf5-1.8.18.tar.gz
    #- cd hdf5-1.8.18
    #- ./configure --prefix=$HOME/chime --enable-cxx
    #- make all install > log 2>&1

    - cd
    - git clone https://github.com/CHIMEFRB/ch_frb_io.git
    - cd ch_frb_io
    - ln -s site/Makefile.local.travis Makefile.local
    - pwd
    - make
    - make install

    - cd
    - git clone https://github.com/kmsmith137/simd_helpers.git
    - cd simd_helpers
    ## Goes with bonsai v10
    - git checkout v4_devel
    - ln -s site/Makefile.local.norootprivs Makefile.local
    - make install

    # - python -c "import distutils.sysconfig; print(distutils.sysconfig.get_python_inc())"
    # #- dpkg -L python-numpy
    # - python -c "import sys; print('\n'.join(sys.path))"
    # - python -c "import numpy; print(numpy.get_include())"
    # - cython --version

    - cd
    #- git clone https://github.com/kmsmith137/simpulse.git
    - git clone https://github.com/dstndstn/simpulse.git
    - cd simpulse
    ### TEMP
    - git checkout travis
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install

    - cd
    - git clone https://github.com/kmsmith137/sp_hdf5.git
    - cd sp_hdf5
    - ln -s site/Makefile.local.linux Makefile.local
    - make install
    - cd
    - mv include/* chime/include/

    - cd
    ###- git clone https://github.com/CHIMEFRB/bonsai.git
    ###- git clone https://github.com/dstndstn/bonsai.git
    ###- cd bonsai
    ### TEMP
    ###- git checkout travis
    - mkdir bonsai
    - wget http://broiler.astrometry.net/~dstn/temp/bonsai-v10.tar.gz
    - tar xzf bonsai-v10.tar.gz
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install

    - cd
    ###- git clone https://github.com/kmsmith137/rf_pipelines.git
    - git clone https://github.com/dstndstn/rf_pipelines.git
    - cd rf_pipelines
    ### TEMP
    #- git checkout hdf5conv-2
    - git checkout hf5conv-2+v15
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install

script:
    - pwd
    - cd $BUILD_DIR
    - pwd
    - ln -s site/Makefile.local.travis Makefile.local
    - ls ~/chime/lib
    - ls ~/chime/include
    - ls ~/lib
    - ls ~/include
    - nm -CD ~/chime/lib/librf_pipelines.so
    
    - make COVERAGE=yes OPTIMIZE=no
    # run some, ahem, unit tests...
    - ./test-l1-rpc &
    - sleep 3
    - python rpc_client.py --shutdown 5555
    - wait
    
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

addons:
  apt:
    packages:
#      - libhdf5-serial-dev   # need newer version for sp_hdf5
      - liblz4-dev
      - libyaml-cpp-dev
      - libboost-dev
      - libjsoncpp-dev  # for rf_pipelines
      - python-numpy    # for rpc_client.py and simpulse
      - libfftw3-dev    # for simpulse
#      - cython          # for simpulse  -- need a version newer than 0.20.1 ?


# Version in trusty is too old (2.1 vs current = 4.2.0)
#      - libzmq-dev
# see ch_frb_io re: libmsgpack-dev

cache:
  directories:
  - $HOME/libzmq
  - $HOME/hdf5
